### ISSUE TITLE
In zazu-ascii-search plugin description "search" replaced with "calculator"

### ISSUE THREAD

**Issue by RettPop** [tinytacoteam/zazu-ascii-search#1]
In zazu-ascii-search plugin description "search" token replaced (by mistake?) with "calculator". Copypasting plugin name to .zazurc.json will lead to plugin loading error.

**Comment by bayleedev** [comment]
I'm not sure what you mean, can you post your `~/.zazurc.json` file here?

**Comment by RettPop** [comment]
It's about "Installation" section of readme.md file. There is "tinytacoteam/zazu-ascii-**calculator**" instead of  "tinytacoteam/zazu-ascii-**search**"

Attaching screenshot.
![screenshot from 2017-01-04 16 57 33](https://cloud.githubusercontent.com/assets/2702414/21648743/4b8a297e-d29f-11e6-8266-76734fb5a57a.png)

**Comment by bayleedev** [comment]
Oh! Silly me. I fixed it, thank you [:
