### ISSUE TITLE
Search Results Not Showing

### ISSUE THREAD

**Issue by Koolstr** [tinytacoteam/zazu-ascii-search#2]
If I try searching for any ascii symbols, none come up. I've even cross-checked with online libraries to ensure I have their names down right. Searching their hex, number, or HTML name doesn't work either.

Is there a keyword that is supposed to be used at the start of the search to initialize looking in this plugin? If so, this plugin needs more thorough documentation...

**Comment by bayleedev** [comment]
You're completely right, I added documentation on how to use this plugin in the readme.

https://github.com/tinytacoteam/zazu-ascii-search#usage
